# Generated by Django 6.0.5 on 2026-05-28 17:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('record_count', models.IntegerField(default=0)),
                ('parsed_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('confidence_avg', models.FloatField(default=0.0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionsRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('raw_record_id', models.CharField(max_length=100)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=50)),
                ('source_format', models.CharField(max_length=50)),
                ('activity_value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('normalized_value', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=50)),
                ('emission_factor', models.FloatField()),
                ('emission_factor_source', models.CharField(max_length=50)),
                ('kgco2e', models.FloatField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('anomaly_sigma', models.FloatField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('provenance', models.JSONField(default=dict)),
                ('fields', models.JSONField(default=dict)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='api.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.tenant')),
            ],
        ),
    ]
