// Backend integration point: replace all mock data with API calls to /api/emissions-records, /api/ingestion-jobs, etc.

export type Scope = 1 | 2 | 3;
export type ReviewStatus = 'pending' | 'approved' | 'rejected' | 'locked';
export type IngestionStatus = 'running' | 'completed' | 'failed' | 'pending';
export type SourceType = 'SAP' | 'Utility' | 'Travel';
export type SourceFormat =
    | 'IDoc XML' | 'CSV/TSV' | 'OData v4' | 'BAPI Output' | 'Utility CSV' | 'PDF OCR' | 'Green Button XML' | 'Manual Entry' | 'Concur SAE CSV' | 'Navan JSON' | 'IATA Itinerary';

export interface EmissionsRecord {
    id: string;
    rawRecordId: string;
    tenantId: string;
    scope: Scope;
    category: string;
    sourceType: SourceType;
    sourceFormat: SourceFormat;
    activityValue: number;
    unit: string;
    normalizedValue: number;
    normalizedUnit: string;
    emissionFactor: number;
    emissionFactorSource: 'DEFRA' | 'EPA' | 'IPCC';
    kgco2e: number;
    periodStart: string;
    periodEnd: string;
    reviewStatus: ReviewStatus;
    confidenceScore: number;
    isAnomalous: boolean;
    anomalySigma?: number;
    isDuplicate: boolean;
    lockedAt?: string;
    lockedBy?: string;
    jobId: string;
    provenance: {
        sourceSystem: string;
        fileName: string;
        ingestionTimestamp: string;
        payloadHash: string;
    };
    fields: Record<string, string>;
}

export interface IngestionJob {
    id: string;
    sourceId: string;
    sourceName: string;
    sourceType: SourceType;
    format: SourceFormat;
    status: IngestionStatus;
    fileName: string;
    recordCount: number;
    parsedCount: number;
    errorCount: number;
    duplicateCount: number;
    startedAt: string;
    completedAt?: string;
    durationMs?: number;
    tenantId: string;
    tenantName: string;
    uploadedBy: string;
    confidenceAvg: number;
}

export const mockIngestionJobs: IngestionJob[] = [
    {
        id: 'job-001',
        sourceId: 'src-sap-001',
        sourceName: 'SAP ECC 6.0 — Plant DE01',
        sourceType: 'SAP',
        format: 'IDoc XML',
        status: 'completed',
        fileName: 'MATDOC_2026_W20_DE01.xml',
        recordCount: 1247,
        parsedCount: 1231,
        errorCount: 16,
        duplicateCount: 8,
        startedAt: '2026-05-27T06:14:22Z',
        completedAt: '2026-05-27T06:19:47Z',
        durationMs: 325000,
        tenantId: 'tenant-001',
        tenantName: 'Meridian Industrial Group',
        uploadedBy: 'priya.nair@meridian.com',
        confidenceAvg: 87,
    },
    {
        id: 'job-002',
        sourceId: 'src-util-001',
        sourceName: 'National Grid — East Midlands',
        sourceType: 'Utility',
        format: 'Utility CSV',
        status: 'completed',
        fileName: 'NG_East_Midlands_Apr2026.csv',
        recordCount: 48,
        parsedCount: 48,
        errorCount: 0,
        duplicateCount: 2,
        startedAt: '2026-05-27T07:02:11Z',
        completedAt: '2026-05-27T07:02:58Z',
        durationMs: 47000,
        tenantId: 'tenant-001',
        tenantName: 'Meridian Industrial Group',
        uploadedBy: 'facilities@meridian.com',
        confidenceAvg: 96,
    },
    {
        id: 'job-003',
        sourceId: 'src-travel-001',
        sourceName: 'Concur Travel — EMEA',
        sourceType: 'Travel',
        format: 'Concur SAE CSV',
        status: 'running',
        fileName: 'concur_sae_may2026_emea.csv',
        recordCount: 0,
        parsedCount: 312,
        errorCount: 4,
        duplicateCount: 0,
        startedAt: '2026-05-27T18:41:05Z',
        tenantId: 'tenant-001',
        tenantName: 'Meridian Industrial Group',
        uploadedBy: 'priya.nair@meridian.com',
        confidenceAvg: 74,
    },
    {
        id: 'job-004',
        sourceId: 'src-sap-002',
        sourceName: 'SAP S/4HANA — Plant UK02',
        sourceType: 'SAP',
        format: 'OData v4',
        status: 'failed',
        fileName: 'odata_pull_2026_05_26',
        recordCount: 0,
        parsedCount: 0,
        errorCount: 1,
        duplicateCount: 0,
        startedAt: '2026-05-26T22:15:00Z',
        completedAt: '2026-05-26T22:15:12Z',
        durationMs: 12000,
        tenantId: 'tenant-001',
        tenantName: 'Meridian Industrial Group',
        uploadedBy: 'system',
        confidenceAvg: 0,
    },
    {
        id: 'job-005',
        sourceId: 'src-util-002',
        sourceName: 'EDF Energy — Sheffield HQ',
        sourceType: 'Utility',
        format: 'PDF OCR',
        status: 'completed',
        fileName: 'EDF_Sheffield_Apr2026_bill.pdf',
        recordCount: 6,
        parsedCount: 5,
        errorCount: 1,
        duplicateCount: 0,
        startedAt: '2026-05-26T14:30:00Z',
        completedAt: '2026-05-26T14:31:44Z',
        durationMs: 104000,
        tenantId: 'tenant-001',
        tenantName: 'Meridian Industrial Group',
        uploadedBy: 'jkumar@meridian.com',
        confidenceAvg: 71,
    },
    {
        id: 'job-006',
        sourceId: 'src-travel-002',
        sourceName: 'Navan — US Corporate',
        sourceType: 'Travel',
        format: 'Navan JSON',
        status: 'completed',
        fileName: 'navan_webhook_batch_20260524',
        recordCount: 203,
        parsedCount: 203,
        errorCount: 0,
        duplicateCount: 1,
        startedAt: '2026-05-24T20:00:01Z',
        completedAt: '2026-05-24T20:00:34Z',
        durationMs: 33000,
        tenantId: 'tenant-001',
        tenantName: 'Meridian Industrial Group',
        uploadedBy: 'system',
        confidenceAvg: 91,
    },
];

export const mockEmissionsRecords: EmissionsRecord[] = [
    {
        id: 'rec-001',
        rawRecordId: 'raw-1001',
        tenantId: 'tenant-001',
        scope: 1,
        category: 'Fuel Combustion — Natural Gas',
        sourceType: 'SAP',
        sourceFormat: 'IDoc XML',
        activityValue: 48200,
        unit: 'kWh',
        normalizedValue: 173520,
        normalizedUnit: 'MJ',
        emissionFactor: 0.18316,
        emissionFactorSource: 'DEFRA',
        kgco2e: 8828.3,
        periodStart: '2026-04-01',
        periodEnd: '2026-04-30',
        reviewStatus: 'pending',
        confidenceScore: 91,
        isAnomalous: false,
        isDuplicate: false,
        jobId: 'job-001',
        provenance: {
            sourceSystem: 'SAP ECC 6.0',
            fileName: 'MATDOC_2026_W20_DE01.xml',
            ingestionTimestamp: '2026-05-27T06:19:47Z',
            payloadHash: 'sha256:a4f2c3d1e8b7',
        },
        fields: {
            cost_center: 'CC-DE01-PROD',
            material_code: 'MAT-NATGAS-001',
            quantity: '48200',
            unit_of_measure: 'kWh',
            transaction_date: '2026-04-30',
            gl_account: '0000410000',
        },
    },
    {
        id: 'rec-002',
        rawRecordId: 'raw-1002',
        tenantId: 'tenant-001',
        scope: 1,
        category: 'Fuel Combustion — Diesel',
        sourceType: 'SAP',
        sourceFormat: 'IDoc XML',
        activityValue: 12400,
        unit: 'L',
        normalizedValue: 447512,
        normalizedUnit: 'MJ',
        emissionFactor: 2.68521,
        emissionFactorSource: 'DEFRA',
        kgco2e: 33297.6,
        periodStart: '2026-04-01',
        periodEnd: '2026-04-30',
        reviewStatus: 'pending',
        confidenceScore: 88,
        isAnomalous: true,
        anomalySigma: 2.8,
        isDuplicate: false,
        jobId: 'job-001',
        provenance: {
            sourceSystem: 'SAP ECC 6.0',
            fileName: 'MATDOC_2026_W20_DE01.xml',
            ingestionTimestamp: '2026-05-27T06:19:47Z',
            payloadHash: 'sha256:b9e4a2f1c6d3',
        },
        fields: {
            cost_center: 'CC-DE01-FLEET',
            material_code: 'MAT-DIESEL-002',
            quantity: '12400',
            unit_of_measure: 'L',
            transaction_date: '2026-04-28',
            gl_account: '0000420000',
        },
    },
    {
        id: 'rec-003',
        rawRecordId: 'raw-1003',
        tenantId: 'tenant-001',
        scope: 2,
        category: 'Electricity — Market-Based',
        sourceType: 'Utility',
        sourceFormat: 'Utility CSV',
        activityValue: 87340,
        unit: 'kWh',
        normalizedValue: 87340,
        normalizedUnit: 'kWh',
        emissionFactor: 0.23314,
        emissionFactorSource: 'DEFRA',
        kgco2e: 20363.9,
        periodStart: '2026-04-01',
        periodEnd: '2026-04-30',
        reviewStatus: 'approved',
        confidenceScore: 97,
        isAnomalous: false,
        isDuplicate: false,
        jobId: 'job-002',
        provenance: {
            sourceSystem: 'National Grid Portal',
            fileName: 'NG_East_Midlands_Apr2026.csv',
            ingestionTimestamp: '2026-05-27T07:02:58Z',
            payloadHash: 'sha256:c3d5e7f2a1b8',
        },
        fields: {
            account_number: 'NG-4472-0089',
            service_address: 'Meridian Plant A, Nottingham NG7 2TU',
            billing_period: '2026-04-01 to 2026-04-30',
            kwh_consumption: '87340',
            tariff_rate: '0.2847',
            demand_charges: '1240.00',
        },
    },
    {
        id: 'rec-004',
        rawRecordId: 'raw-1004',
        tenantId: 'tenant-001',
        scope: 2,
        category: 'Electricity — Location-Based',
        sourceType: 'Utility',
        sourceFormat: 'Utility CSV',
        activityValue: 87340,
        unit: 'kWh',
        normalizedValue: 87340,
        normalizedUnit: 'kWh',
        emissionFactor: 0.19338,
        emissionFactorSource: 'DEFRA',
        kgco2e: 16887.7,
        periodStart: '2026-04-01',
        periodEnd: '2026-04-30',
        reviewStatus: 'approved',
        confidenceScore: 97,
        isAnomalous: false,
        isDuplicate: false,
        jobId: 'job-002',
        provenance: {
            sourceSystem: 'National Grid Portal',
            fileName: 'NG_East_Midlands_Apr2026.csv',
            ingestionTimestamp: '2026-05-27T07:02:58Z',
            payloadHash: 'sha256:c3d5e7f2a1b8',
        },
        fields: {
            account_number: 'NG-4472-0089',
            service_address: 'Meridian Plant A, Nottingham NG7 2TU',
            billing_period: '2026-04-01 to 2026-04-30',
            kwh_consumption: '87340',
            tariff_rate: '0.2847',
            demand_charges: '1240.00',
        },
    },
    {
        id: 'rec-005',
        rawRecordId: 'raw-1005',
        tenantId: 'tenant-001',
        scope: 3,
        category: 'Cat 6 — Business Travel (Air)',
        sourceType: 'Travel',
        sourceFormat: 'Concur SAE CSV',
        activityValue: 4820,
        unit: 'km',
        normalizedValue: 4820,
        normalizedUnit: 'km',
        emissionFactor: 0.15532,
        emissionFactorSource: 'DEFRA',
        kgco2e: 748.6,
        periodStart: '2026-04-15',
        periodEnd: '2026-04-15',
        reviewStatus: 'pending',
        confidenceScore: 78,
        isAnomalous: false,
        isDuplicate: false,
        jobId: 'job-003',
        provenance: {
            sourceSystem: 'Concur Travel EMEA',
            fileName: 'concur_sae_may2026_emea.csv',
            ingestionTimestamp: '2026-05-27T18:41:05Z',
            payloadHash: 'sha256:d4e6f8a2c0b1',
        },
        fields: {
            traveler_id: 'EMP-00342',
            origin_iata: 'LHR',
            destination_iata: 'FRA',
            trip_date: '2026-04-15',
            distance_km: '4820 (calculated)',
            travel_class: 'Economy',
            transport_mode: 'Air',
        },
    },
    {
        id: 'rec-006',
        rawRecordId: 'raw-1006',
        tenantId: 'tenant-001',
        scope: 3,
        category: 'Cat 6 — Business Travel (Air)',
        sourceType: 'Travel',
        sourceFormat: 'Concur SAE CSV',
        activityValue: 11240,
        unit: 'km',
        normalizedValue: 11240,
        normalizedUnit: 'km',
        emissionFactor: 0.19526,
        emissionFactorSource: 'DEFRA',
        kgco2e: 2194.7,
        periodStart: '2026-04-18',
        periodEnd: '2026-04-18',
        reviewStatus: 'pending',
        confidenceScore: 62,
        isAnomalous: true,
        anomalySigma: 3.2,
        isDuplicate: false,
        jobId: 'job-003',
        provenance: {
            sourceSystem: 'Concur Travel EMEA',
            fileName: 'concur_sae_may2026_emea.csv',
            ingestionTimestamp: '2026-05-27T18:41:05Z',
            payloadHash: 'sha256:e5f7a9b3c2d4',
        },
        fields: {
            traveler_id: 'EMP-00198',
            origin_iata: 'LHR',
            destination_iata: 'SIN',
            trip_date: '2026-04-18',
            distance_km: '11240 (IATA lookup)',
            travel_class: 'Business',
            transport_mode: 'Air',
        },
    },
    {
        id: 'rec-007',
        rawRecordId: 'raw-1007',
        tenantId: 'tenant-001',
        scope: 3,
        category: 'Procurement — Indirect Materials',
        sourceType: 'SAP',
        sourceFormat: 'CSV/TSV',
        activityValue: 24800,
        unit: 'kg',
        normalizedValue: 24800,
        normalizedUnit: 'kg',
        emissionFactor: 1.84,
        emissionFactorSource: 'EPA',
        kgco2e: 45632,
        periodStart: '2026-04-01',
        periodEnd: '2026-04-30',
        reviewStatus: 'pending',
        confidenceScore: 55,
        isAnomalous: true,
        anomalySigma: 2.4,
        isDuplicate: false,
        jobId: 'job-001',
        provenance: {
            sourceSystem: 'SAP ECC 6.0',
            fileName: 'MATDOC_2026_W20_DE01.xml',
            ingestionTimestamp: '2026-05-27T06:19:47Z',
            payloadHash: 'sha256:f6a8b0c4d5e7',
        },
        fields: {
            cost_center: 'CC-DE01-PROC',
            material_code: 'MAT-STEEL-018',
            quantity: '24800',
            unit_of_measure: 'kg',
            transaction_date: '2026-04-22',
            gl_account: '0000500000',
        },
    },
    {
        id: 'rec-008',
        rawRecordId: 'raw-1008',
        tenantId: 'tenant-001',
        scope: 2,
        category: 'Electricity — Market-Based',
        sourceType: 'Utility',
        sourceFormat: 'PDF OCR',
        activityValue: 12840,
        unit: 'kWh',
        normalizedValue: 12840,
        normalizedUnit: 'kWh',
        emissionFactor: 0.23314,
        emissionFactorSource: 'DEFRA',
        kgco2e: 2993.5,
        periodStart: '2026-04-01',
        periodEnd: '2026-04-30',
        reviewStatus: 'pending',
        confidenceScore: 43,
        isAnomalous: false,
        isDuplicate: false,
        jobId: 'job-005',
        provenance: {
            sourceSystem: 'EDF Energy Portal',
            fileName: 'EDF_Sheffield_Apr2026_bill.pdf',
            ingestionTimestamp: '2026-05-26T14:31:44Z',
            payloadHash: 'sha256:a1b2c3d4e5f6',
        },
        fields: {
            account_number: 'EDF-88324-001',
            service_address: 'Meridian Sheffield HQ, S1 2HH',
            billing_period: '2026-04-01 to 2026-04-30',
            kwh_consumption: '12840',
            tariff_rate: '0.3124',
            demand_charges: '340.50',
        },
    },
    {
        id: 'rec-009',
        rawRecordId: 'raw-1009',
        tenantId: 'tenant-001',
        scope: 3,
        category: 'Cat 6 — Business Travel (Rail)',
        sourceType: 'Travel',
        sourceFormat: 'Navan JSON',
        activityValue: 640,
        unit: 'km',
        normalizedValue: 640,
        normalizedUnit: 'km',
        emissionFactor: 0.04115,
        emissionFactorSource: 'DEFRA',
        kgco2e: 26.3,
        periodStart: '2026-04-20',
        periodEnd: '2026-04-20',
        reviewStatus: 'locked',
        confidenceScore: 94,
        isAnomalous: false,
        isDuplicate: false,
        lockedAt: '2026-05-10T09:15:00Z',
        lockedBy: 'admin.jones@meridian.com',
        jobId: 'job-006',
        provenance: {
            sourceSystem: 'Navan US Corporate',
            fileName: 'navan_webhook_batch_20260524',
            ingestionTimestamp: '2026-05-24T20:00:34Z',
            payloadHash: 'sha256:b2c4d6e8f0a2',
        },
        fields: {
            traveler_id: 'EMP-00521',
            origin_iata: 'MAN',
            destination_iata: 'EUS',
            trip_date: '2026-04-20',
            distance_km: '640 (calculated)',
            travel_class: 'Standard',
            transport_mode: 'Rail',
        },
    },
    {
        id: 'rec-010',
        rawRecordId: 'raw-1010',
        tenantId: 'tenant-001',
        scope: 1,
        category: 'Fuel Combustion — LPG',
        sourceType: 'SAP',
        sourceFormat: 'IDoc XML',
        activityValue: 3200,
        unit: 'kg',
        normalizedValue: 149760,
        normalizedUnit: 'MJ',
        emissionFactor: 2.94396,
        emissionFactorSource: 'DEFRA',
        kgco2e: 9420.7,
        periodStart: '2026-04-01',
        periodEnd: '2026-04-30',
        reviewStatus: 'rejected',
        confidenceScore: 34,
        isAnomalous: false,
        isDuplicate: true,
        jobId: 'job-001',
        provenance: {
            sourceSystem: 'SAP ECC 6.0',
            fileName: 'MATDOC_2026_W20_DE01.xml',
            ingestionTimestamp: '2026-05-27T06:19:47Z',
            payloadHash: 'sha256:c3d5e7f9a1b3',
        },
        fields: {
            cost_center: 'CC-DE01-HEAT',
            material_code: 'MAT-LPG-005',
            quantity: '3200',
            unit_of_measure: 'kg',
            transaction_date: '2026-04-25',
            gl_account: '0000415000',
        },
    },
    {
        id: 'rec-011',
        rawRecordId: 'raw-1011',
        tenantId: 'tenant-001',
        scope: 3,
        category: 'Cat 6 — Business Travel (Air)',
        sourceType: 'Travel',
        sourceFormat: 'Concur SAE CSV',
        activityValue: 8620,
        unit: 'km',
        normalizedValue: 8620,
        normalizedUnit: 'km',
        emissionFactor: 0.17841,
        emissionFactorSource: 'DEFRA',
        kgco2e: 1537.9,
        periodStart: '2026-05-03',
        periodEnd: '2026-05-03',
        reviewStatus: 'pending',
        confidenceScore: 81,
        isAnomalous: false,
        isDuplicate: false,
        jobId: 'job-003',
        provenance: {
            sourceSystem: 'Concur Travel EMEA',
            fileName: 'concur_sae_may2026_emea.csv',
            ingestionTimestamp: '2026-05-27T18:41:05Z',
            payloadHash: 'sha256:d4e6f8a0b2c5',
        },
        fields: {
            traveler_id: 'EMP-00089',
            origin_iata: 'CDG',
            destination_iata: 'JFK',
            trip_date: '2026-05-03',
            distance_km: '8620 (IATA lookup)',
            travel_class: 'Premium Economy',
            transport_mode: 'Air',
        },
    },
    {
        id: 'rec-012',
        rawRecordId: 'raw-1012',
        tenantId: 'tenant-001',
        scope: 2,
        category: 'Electricity — Market-Based',
        sourceType: 'Utility',
        sourceFormat: 'Green Button XML',
        activityValue: 54780,
        unit: 'kWh',
        normalizedValue: 54780,
        normalizedUnit: 'kWh',
        emissionFactor: 0.23314,
        emissionFactorSource: 'DEFRA',
        kgco2e: 12775.8,
        periodStart: '2026-03-01',
        periodEnd: '2026-03-31',
        reviewStatus: 'approved',
        confidenceScore: 99,
        isAnomalous: false,
        isDuplicate: false,
        jobId: 'job-002',
        provenance: {
            sourceSystem: 'Green Button API',
            fileName: 'greenbutton_march2026.xml',
            ingestionTimestamp: '2026-05-01T08:00:00Z',
            payloadHash: 'sha256:e5f7a9b1c3d6',
        },
        fields: {
            account_number: 'GB-9981-0012',
            service_address: 'Meridian Warehouse B, Leicester LE1 3TQ',
            billing_period: '2026-03-01 to 2026-03-31',
            kwh_consumption: '54780',
            tariff_rate: '0.2701',
            demand_charges: '890.00',
        },
    },
];

// Overview metrics
export const overviewMetrics = {
    totalScope1: 51546.6,
    totalScope2: 52020.9,
    totalScope3: 50139.5,
    totalAll: 153707,
    pendingCount: 47,
    anomalyCount: 8,
    ingestionSuccessRate: 98.7,
    duplicateRejectionCount: 11,
    yoyDelta: -4.2, // percent
    activeJobs: 1,
};

export const weeklyTrendData = [
    { week: 'W08', scope1: 48200, scope2: 41300, scope3: 39800 },
    { week: 'W09', scope1: 51400, scope2: 43800, scope3: 44200 },
    { week: 'W10', scope1: 47800, scope2: 40100, scope3: 41600 },
    { week: 'W11', scope1: 53200, scope2: 44900, scope3: 46800 },
    { week: 'W12', scope1: 49100, scope2: 42200, scope3: 43100 },
    { week: 'W13', scope1: 55800, scope2: 47300, scope3: 48900 },
    { week: 'W14', scope1: 50400, scope2: 43600, scope3: 44500 },
    { week: 'W15', scope1: 46700, scope2: 39800, scope3: 40200 },
    { week: 'W16', scope1: 52300, scope2: 45100, scope3: 47300 },
    { week: 'W17', scope1: 48900, scope2: 41700, scope3: 42800 },
    { week: 'W18', scope1: 54100, scope2: 46200, scope3: 49600 },
    { week: 'W19', scope1: 51546, scope2: 52020, scope3: 50139 },
];

export const scopeBreakdownData = [
    { name: 'Scope 1', value: 51546.6, fill: '#f59e0b' },
    { name: 'Scope 2', value: 52020.9, fill: '#3b82f6' },
    { name: 'Scope 3', value: 50139.5, fill: '#2dd4bf' },
];